name: "Setup the toolchain"

runs:
  using: "composite"
  steps:
    - name: Hash action workspace
      id: hash
      shell: bash
      run: |
        echo "hash=$(cat bootstrap.sh | sha1sum | cut -d' ' -f1)" >> "$GITHUB_OUTPUT"

    - name: Restore toolchain cache
      uses: actions/cache/restore@v4
      id: cache
      with:
        path: ${{ github.action_path }}/.cache
        key: toolchain-${{ steps.hash.outputs.hash }}

    - name: Run bootstrap.sh
      shell: bash
      run: |
        OUTPUT="$(source "${{ github.action_path }}/bootstrap.sh")"
        eval "$OUTPUT"
        
        echo "$OUTPUT" >> "$GITHUB_ENV"
        echo "$TOOLCHAIN_PATH" >> "$GITHUB_PATH"
        echo "$OUTPUT"

    - name: Save toolchain cache
      uses: actions/cache/save@v4
      if: steps.cache.outputs.cache-hit != 'true'
      with:
        path: ${{ github.action_path }}/.cache
        key: toolchain-${{ steps.hash.outputs.hash }}

    - name: Show GCC info
      shell: bash
      run: |
        ${{ env._5735245e1d5c433a661f2084a6657db18b3ec033 }}/${{ env.TOOLCHAIN_CROSS }}-gcc -v
