name: "Setup the toolchain"

runs:
  using: "composite"
  steps:
    - name: Hash action workspace
      id: hash
      shell: bash
      run: |
        echo "hash=$(find "${{ github.action_path }}" -type f -exec sha1sum {} \; | sha1sum | cut -d' ' -f1)" >> "$GITHUB_OUTPUT"

    - name: Cache toolchain
      uses: actions/cache@v4
      with:
        path: ${{ github.action_path }}
        key: toolchain-${{ steps.hash.outputs.hash }}

    - name: Run bootstrap.sh and export results
      shell: bash
      run: |
        source "${{ github.action_path }}/bootstrap.sh"

        set -x
        
        echo "_5735245e1d5c433a661f2084a6657db18b3ec033=$_5735245e1d5c433a661f2084a6657db18b3ec033" >> "$GITHUB_ENV"
        echo "TOOLCHAIN_CROSS=$TOOLCHAIN_CROSS" >> $GITHUB_ENV

    - name: Show GCC info
      shell: bash
      run: |
        ${{ env._5735245e1d5c433a661f2084a6657db18b3ec033 }}/${{ env.TOOLCHAIN_CROSS }}-gcc -v
